create schema IF NOT EXISTS orca;
set schema orca;

create table IF NOT EXISTS INSUR_APPLICATIONS  (
	 APP_NUM CHAR(25) NOT NULL
	,NAME CHAR(25) NOT NULL
	,GENDER CHAR(2) NOT NULL -- Enum conversion
	,APP_STATUS CHAR(10) NOT NULL
	,CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,PRIMARY KEY (APP_NUM)
)
;
INSERT INTO INSUR_APPLICATIONS (APP_NUM, NAME,GENDER, APP_STATUS) VALUES
      ('RA0001', 'Mr Tomato' ,'M', 'INITIAL'),
      ('RA0002', 'Ms Potato' ,'F',  'ONHOLD')
;


-- -----------------------------
create table IF NOT EXISTS MUNICIPALITY  (
	 POSTAL_CD CHAR(25)
	,MUNICIPALITY_CD INTEGER NOT NULL
	,MUNICIPALITY_DESC VARCHAR(25) NOT NULL
	,PRIMARY KEY (POSTAL_CD)
)
;
INSERT INTO MUNICIPALITY (POSTAL_CD, MUNICIPALITY_CD, MUNICIPALITY_DESC) VALUES
      ('A1AA1A', 123 ,  'ot'),
      ('111111', 234, 'ot')
;

-- ------------------
create table IF NOT EXISTS NOTES  (
	 ID INTEGER NOT NULL
	,CODE CHAR(1) NOT NULL
	,INS_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,NOTE VARCHAR(225) NOT NULL
	,PRIMARY KEY (ID,CODE,INS_TS)
)
;

INSERT INTO NOTES (ID, CODE, INS_TS, NOTE) VALUES
      (1, 'E' ,TIMESTAMP '2017-11-28 21:20:09.304' , 'LORIM IPSUM'),
      (1, 'E' ,TIMESTAMP '2017-11-28 21:20:09.305' ,  'The dog'),
      (1, 'A' ,TIMESTAMP '2017-11-28 21:20:09.305' ,  'The babe'),
      (2, 'E' ,TIMESTAMP '2017-11-28 21:20:09.305' ,  'The thomfi')
;